# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mostly Text
tagline:             'Recounts of Existence and Code'
description:         "Jamie Shen is a curious writer of virtual space. He writes about technology and the human experience from his perspective."
url:                 http://blog.jmeshen.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jamie Shen
  url:               https://twitter.com/jmeshen
  email:             hello@jmeshen.com

# Custom vars
version:             1.0.0
